<?php

namespace TicTacToe;

/**
 * Move, generated by a person.
 *
 * @package TicTacToe
 */
class HumanMove implements Move
{
    private $move;

    public function __construct()
    {
        $this->move = new ValidMove(
            new InteractiveMove(
                new InputMatching(
                    '/^\d \d$/',
                    new StdinInput('Enter move ("0 0" is the top-left corner, "2 2" is bottom right): ')
                )
            )
        );
    }

    /**
     * {@inheritdoc}
     */
    public function exists()
    {
        return $this->move->exists();
    }

    /**
     * {@inheritdoc}
     */
    public function toTuple()
    {
        return $this->move->toTuple();
    }

    /**
     * {@inheritdoc}
     */
    public function next(array $board)
    {
        return $this->move->next($board);
    }
}
